const PRODUCTOS = [{
    id: 1,
    nombre: "BANQUITO",
    precio: 5700,
    imgFile: "./images/banquito_inicio.png",
    prodCar: 1,
    stock: 10,
    alt: "ProductoBanquito",
    direc: "./pages/banquito.html",
    cantidad: 1,
  },
  {
    id: 2,
    nombre: "CANDELABRO",
    precio: 13000,
    imgFile: "./images/candelabro_inicio.jpg",
    prodCar: 1,
    stock: 8,
    alt: "ProductoCandelabro",
    direc: "./pages/candelabro.html",
    cantidad: 1,
  },
  {
    id: 3,
    nombre: "BANDEJAHEXAGONAL",
    precio: 8900,
    imgFile: "./images/bandeja_hex_inicio.jpg",
    prodCar: 1,
    stock: 3,
    alt: "ProductoBandejaHexagonal",
    direc: "./pages/hexagonal.html",
    cantidad: 1,
  },
  {
    id: 4,
    nombre: "BANDEJAOCTOGONAL",
    precio: 11000,
    imgFile: "./images/bandeja_octo_inicio.png",
    prodCar: 1,
    stock: 4,
    alt: "ProductoBandejaOctogonal",
    direc: "./pages/octogonal.html",
    cantidad: 1,
  },
  {
    id: 5,
    nombre: "ESTANTE",
    precio: 16000,
    imgFile: "./images/estante_inicio.png",
    prodCar: 2,
    stock: 2,
    alt: "ProductoEstante",
    direc: "./pages/estante.html",
    cantidad: 1,
  },
  {
    id: 6,
    nombre: "ESPEJO",
    precio: 19000,
    imgFile: "./images/render_espejo_inicio.png",
    prodCar: 1,
    stock: 6,
    alt: "ProductoEspejo",
    direc: "./pages/espejo.html",
    cantidad: 1,
  },
  {
    id: 7,
    nombre: "MESAOCTOGONAL",
    precio: 25000,
    imgFile: "./images/mesita_inicio.png",
    prodCar: 1,
    stock: 6,
    alt: "ProductoMesaOcotogonal",
    direc: "./pages/mesa.html",
    cantidad: 1,
  },
]

const eJSON = JSON.stringify(PRODUCTOS)
localStorage.setItem("productosJSON", eJSON)